### ISSUE TITLE
Laravel 5.1 Upgrade

### ISSUE THREAD

**Issue by iBotPeaches** [TrackerNetwork/DestinyStatus#10]
Lots of the talk on Reddit/chat already has been upgrading to Laravel 5.1, I don't see any immediate concern to upgrade, but if the production server has PHP 5.5 then I don't see why not.

The upgrade path has to go `4.2` -> `5.0` -> `5.1` (The `4.2` -> `5.0`) jump is the big one, but I thought I would document what caught my eye in looking at this upgrade.
- [x] Update controllers w/ proper namespacing
- [x] The PSR4 `app/destiny` namespace is already registered so should work fine.
- [x] The 5.1 ENV systems means all configurations need to be moved to `.env` and abstracted in loading.
- [x] The AssetBuster 4.2 dependency doesn't exist in 5.1, because of the addition of Laravel's exlixir.
- [x] Guzzlehttp 5.0 _might_ work in 5.1, but maybe the new version required is 6.0 which has changes to syntax

The real problem area is the Exlixir/Asset manager change. Lots of changes required there.

**Comment by iBotPeaches** [comment]
This is done. I tried to work on the site to prep for ROI stuff and generally give it some much needed love, but Laravel 4.2 and PHP7 (my local dev) don't work anymore.

So I upgraded to Laravel 5.1 (LTS). 4.2 -> 5.0 was a bitch, and 5.0 to 5.1 was easy. Lots of things were changed and I removed all the bower stuff in favour of Laravel elixir.

https://github.com/iBotPeaches/DestinyStatus/tree/feature/laravel51

I need to clean it up more and then work on the /v2/ endpoints for public advisors and fix the Arena problem.

**Comment by bladefist** [comment]
@iBotPeaches Ok, let us know, would love to merge these in.  Will I need to update anything on the servers?

**Comment by iBotPeaches** [comment]
Shouldn't need to. Same requirements as 4.2, except new minimum of PHP to 5.5. The main difference is just no more bower or modified local assets. So you just have to run `npm install` then `gulp --production` to get the js/css compiled.

The `.env` file is the only file that changes between deployments. 

I have a whole new homepage locally, I'll make a PR when thats ready.

**Comment by iBotPeaches** [comment]
Yep, this is done and on production. Merged into master.
