### ISSUE TITLE
OAuth Sign-In fails on Preferred Account page

### ISSUE THREAD

**Issue by sgtfrankieboy** [TrackerNetwork/DestinyStatus#101]
When trying to sign into DestinyStatus using OAuth, I get redirected to: 

`https://destinystatus.com/preferred-account`

This page returns the following error: "Whoops, looks like something went wrong."

I am assuming it has something to do with having multiple accounts attached? I have my XBL, PSN and Battle.net accounts linked. However only have a Destiny 2 account/character for XBL.

**Comment by iBotPeaches** [comment]
Issue was because Bungie accounts with multiple Destiny accounts that have not set a preferred didn't have the account relation, thus failed. Fixed with two above commits.
