### ISSUE TITLE
Total Kills on clan PvE page is incorrect

### ISSUE THREAD

**Issue by stephenross** [TrackerNetwork/DestinyStatus#102]
Looking at the clan PvE total kills page, I can see that there is a number that supposedly indicates the total number of kills a player has, but does not match the number that I am able to see with my kill tracker ghost. I will take a look at the API to see if there is anything missing that might account for it (It looks like it might be only showing kills for a single character instead of all of them)

**Comment by iBotPeaches** [comment]
I was going to look into this, but it appears the clan leaderboard endpoint is now under maintenance. At least character stats is working again.

I'll sit on this until that endpoint is back up and running.

**Comment by stephenross** [comment]
Awesome. I would offer assistance, but haven't done anything PHP in many years.

**Comment by iBotPeaches** [comment]
Okay, clan endpoint is up finally. I am doing nothing with this endpoint, but just displaying it from Bungie. So it appears a mismatch might be a bug in Bungie or misunderstanding of the data it provides.

**Comment by iBotPeaches** [comment]
Sorry for notification years later. I double checked this and just showing what Bungie API provides. Closing to clean up tracker, as something outside my control.
