### ISSUE TITLE
PSN and XBL username with spaces or underscores not longer working

### ISSUE THREAD

**Issue by Flatlyn** [TrackerNetwork/DestinyStatus#107]
Valid usernames on from Xbox that can contain a space, and valid usernames from PSN that can contain an underscore are returning Not Found Errors. The error log page shows that if a username with an space/underscore/etc is entered the system is replacing those characters before searching. 

For example, "User Name", which would be a valid XBL username format, returns a not found error but showing the system searched for "User-Name", which is also a valid XBL username but different and unique to "User Name". The same example occurs on PSN with underscores. 

The error returned is "The player 'user-name' on 'xbl' could not be found." format rather than the usual "Sorry. The gamertag user_name could not be found." format.

**Comment by iBotPeaches** [comment]
Yeah, I really messed things up on my last commit to fix the "#" issue on PC. I will try and fix all these up and update the test suite tonight/tomorrow.

**Comment by iBotPeaches** [comment]
https://github.com/TrackerNetwork/DestinyStatus/commit/35b8e7ecb31a8c14170fca118005131a4a618bb0 This should be fixed. Deploying now.
