### ISSUE TITLE
Stats are incorrect for hunter

### ISSUE THREAD

**Issue by taiyangc** [TrackerNetwork/DestinyStatus#108]
My stats for hunter is incorrect. My psn id is `expexp`. I do not have such a ridiculous k/d or that amount of pvp kills (yet). See below for obvious wrong stats...

<img width="325" alt="screen shot 2017-10-28 at 12 47 54 am" src="https://user-images.githubusercontent.com/1467354/32132608-51c655ea-bb7b-11e7-869e-2e1270c3ad34.png">

**Comment by iBotPeaches** [comment]
Yep, this is an upstream bug by Bungie - https://github.com/Bungie-net/api/issues/253

Whenever that gets deployed, things should start working again. Sorry for the inconvenience.

**Comment by taiyangc** [comment]
Thanks for the explanation!
