### ISSUE TITLE
Non-latin characters generate "Bad Request"

### ISSUE THREAD

**Issue by Flatlyn** [TrackerNetwork/DestinyStatus#109]
If you search for a username that contains certain non-latin characters it will generate a "Bungie Says:  Bad Request" error. This would seem to be an issue since the PC launch of Destiny 2 since Battle.net tags can contain a wider variety of characters than PSN/XBL. The character in the username I was looking up that generated the bad request was "Ŧ".

The same username checked on destinytracker returns the user without issue. I don't want to post the username I was searching here since it's not my own but I can provide it privately if required for verification/testing. 

Also usernames with Chinese characters–again an issue since the PC release with Battle.net guardians possibly having Chinese usernames–don't return a guardian. Chinese characters may be a bungie API limitation though as none of the other trackers, including destinytracker, can find them either.

**Comment by iBotPeaches** [comment]
Confirmed.

This is my example

```
Username: Grëëm#1623
```

I will work to get this resolved and deployed.
