### ISSUE TITLE
500 error when accessing http://d1.destinystatus.com/

### ISSUE THREAD

**Issue by m-paternostro** [TrackerNetwork/DestinyStatus#118]
Unfortunately all information I have is what I wrote on the subject.

Thank you for keeping tools for D1!

**Comment by iBotPeaches** [comment]
Thanks for alert. It seems something is wrong with the manifest download from D1. I'll admit I'm not sure what I can promise with D1, but I'll boot up the project tonight locally and see if I can't fix.

Note to self, looks like encoding issue with manifest download.
```
                                                                                        
  [InvalidArgumentException]                                                            
  Unable to parse JSON data: JSON_ERROR_CTRL_CHAR - Unexpected control character found  
```

**Comment by m-paternostro** [comment]
Thank for trying to fix it!

**Comment by iBotPeaches** [comment]
Should be back. Thanks for note. Had a corrupted cookie due to running out of disc space.

**Comment by m-paternostro** [comment]
It's back! Thank you!
