### ISSUE TITLE
Logistics

### ISSUE THREAD

**Issue by iBotPeaches** [TrackerNetwork/DestinyStatus#120]
I'm playing D2 again, so gonna work on this as a quarantine project.

@bladefist / @sgtfrankieboy - can you add me as whatever role on github in this repo allows me to add webhooks/deployment keys/configure github actions? I want to automate releases using actions and remove this styleci thing

Also,

> To continue contributing to this team account in TweetDeck, you or the team account’s owner need to visit Twitter’s website and agree to the updated Terms and Privacy Policy. 

Can you agree to the Twitter account ToS change? I can't use through Tweetdeck anymore.

**Comment by iBotPeaches** [comment]
Also exploring upgrading that server that houses 
 * d1.destinystatus.com
 * destinystatus.com
 * bots.tracker.network

to php74, but pinged @xenos360 to be sure bots.tracker.network can support that.

**Comment by sgtfrankieboy** [comment]
I've bumped you up to the "Admin" role, you should be able to do everything now. 

I'm looking into the twitter access thing.
