### ISSUE TITLE
Cache Name -> Id lookup

### ISSUE THREAD

**Issue by bladefist** [TrackerNetwork/DestinyStatus#17]

**Comment by iBotPeaches** [comment]
Every profile hit, we send 2 requests to Bungie. 

```
destiny/stats/account/1/4611686018430553461/?lc=en&groups%5B0%5D=General (545.71ms)
destiny/1/account/4611686018430553461/summary/?lc=en (558.4ms)
```

They are relatively clunky and don't need to be re-used. The connection between platform/gamertag/membershipId can be cached.

We can check cache pool, if hit. Return membershipId and whatever else it needs.

If not, hit api. No harm no foul. Repeat visitors will have n-2 requests.

**Comment by iBotPeaches** [comment]
![speed](https://cloud.githubusercontent.com/assets/611784/18913064/c2f2ac50-8553-11e6-91eb-aa19db91f9e3.png)

The merge of dev into master fixes this. Properly applies cache to search/lookup.
