### ISSUE TITLE
Xur panel on homepage needs inventory like PoE boxes

### ISSUE THREAD

**Issue by bladefist** [TrackerNetwork/DestinyStatus#2]

**Comment by iBotPeaches** [comment]
Peeking at the current home page. We have 2 rows of 3 columns that go

CURRENT EVENT ...
DAILY - WEEKLY - NIGHTFALL
POE 32 - POE 34 - POE 35

Granted Xur is only here for like 48 hours every week. There is no easy way to add this without pushing this index page to 4 rows with this new row only having one column.

Not sure if there is an alternative to this. Hooking onto the Xur current event and changing message to "Xur is here - Inventory [hyperlink]" to its own advisor page (would allow extending for other advisors without cluttering the site). Just some opinions / discussion.

**Comment by iBotPeaches** [comment]
https://cloud.githubusercontent.com/assets/611784/18585069/bc00d964-7be2-11e6-8bd6-69aa9d54562d.JPG

Fixed by merge of dev into master.
