### ISSUE TITLE
pretty numbers on stats page

### ISSUE THREAD

**Issue by iBotPeaches** [TrackerNetwork/DestinyStatus#22]
So sometimes for me, looking at 8 digits in a row 00000000 is difficult for me to process what that number is. Simply creating a new mutator for formattedValues which allows us to return formatted numbers like so.

![commas](https://cloud.githubusercontent.com/assets/611784/12144087/14f9a0b0-b44b-11e5-83e2-b724e23175e1.png)

vs the old

![old](https://cloud.githubusercontent.com/assets/611784/12144102/2c78f4d4-b44b-11e5-8b8b-296379f85fc3.png)

However, then I realized not all locales use this method. Maybe a locale aware (just read request heads for `Accept-Language` or `HTTP_ACCEPT_LANGUAGE` - I think browsers sent this). If we can find a locale based on those properties we can instruct the framework to use it.

**Comment by bladefist** [comment]
A comma would be incremental progress. Could circle back around and make it locale aware later.

**Comment by frodeknutsen** [comment]
I used English formatting of these numbers but got a lot of complaints from users. This is why there was no formatting. Yep. Go figure
