### ISSUE TITLE
Rumble grimoire not showing

### ISSUE THREAD

**Issue by hmsaleem** [TrackerNetwork/DestinyStatus#26]
I know the doubles grimoire is hidden, but the rumble isn't visible.

http://destinystatus.com/psn/royaldruk/grimoire

I have not won a single rumble match and that card should still be there.

**Comment by iBotPeaches** [comment]
Strange. You have 5 pts already in Rumble, but 0 wins, and registered kills/deaths in it. So the `RankCollection` system sees a 0 value, but non-zero point value and removes it.

I could simply check if a `RankCollection` exists, as it does for `Match Wins`, but does not for `Kills/Deaths` and that should do it.

**Comment by hmsaleem** [comment]
This has been an bug form the very start. I had reached out the developer quite a while back, before the open source. I think it comes up when there is atleast  a win. But before that it remins hidden.

**Comment by iBotPeaches** [comment]
Yeah was a strange set of conditions that led to this. If you had won 1 game of Rumble it would have fixed itself :p

Fixed either way, pull request is in.

**Comment by hmsaleem** [comment]
If only I was good enough for rumble! 

Thanks though! I love this website, glad you guys have taken over!
