### ISSUE TITLE
Missing images for kinetic damage

### ISSUE THREAD

**Issue by hmsaleem** [TrackerNetwork/DestinyStatus#28]
Another minor bug.

Some of the guns are somehow not showing the image associated with kinetic damage.

![screen shot 2016-01-10 at 1 28 45 am](https://cloud.githubusercontent.com/assets/3317445/12220278/f6688cfa-b739-11e5-8c42-c68678c38973.png)

**Comment by iBotPeaches** [comment]
Hmm. Kinetic damage corresponds to `id` 1. In this case ToM returns 0. This means technically it isn't Kinetic.

Needs more research.
