### ISSUE TITLE
Ghost Fragment: Vex 5 -> PS Exclusive

### ISSUE THREAD

**Issue by Ackis** [TrackerNetwork/DestinyStatus#30]
This ghost should be flagged as PS Exclusive.  You can only get it in the PS only strike.

**Comment by iBotPeaches** [comment]
I thought about this when I made that commit, but myself as an xbox player could glitch into the area and obtain this card.

**Comment by DOOMenico** [comment]
I see your point iBotPeaches but the capability to glitch into the map to retrieve the ghost it's not an intended behaviour of the game. As linear approach could be better to flag the ghost as Ackis suggests.

**Comment by sgtfrankieboy** [comment]
I've updated this in commit edb5409.
