### ISSUE TITLE
Unicode character urldecoding

### ISSUE THREAD

**Issue by cwild** [TrackerNetwork/DestinyStatus#32]
Firstly, I think your site is great and has been very useful!

I noticed a problem with the grimoire generation of the following URL:
http://db.destinytracker.com/grimoire/enemies/exalted-hive/ir-yut-the-deathsinger

The generated URL is:
http://db.destinytracker.com/grimoire/enemies/exalted-hive/ir-yt-the-deathsinger

Having had a quick glance over the codebase (familiarity with Laravel is minimal), I noticed that the following could potentially strip the character away:
https://github.com/TrackerNetwork/DestinyStatus/blob/b8d222502537570d1169cd6ab69cbf63ecda2c48/app/helpers.php#L39-L57

Apologies as I have not got a development setup so was unable to test this more thoroughly.

**Comment by iBotPeaches** [comment]
`iconv` is supposed to find the nearest ASCII character, which should of returned `u` instead of stripping it. Appears something is amiss, maybe the production server lost the `iconv` extension. Will investigate, thanks for report.

**Comment by sgtfrankieboy** [comment]
Thanks for notifying, I also see that Grimoire cards that contain `'` are not properly trimmed.

**Comment by iBotPeaches** [comment]
Very late, but investigating this. We generate

```
http://db.destinytracker.com/grimoire/enemies/the-taken/noru39usk-servant-of-oryx
```

but correct URL lives at

```
http://db.destinytracker.com/grimoire/enemies/the-taken/noruusk-servant-of-oryx
```

Need to update tests for this and figure out whats going on.
