### ISSUE TITLE
reputation icons are broken

### ISSUE THREAD

**Issue by adcurtin** [TrackerNetwork/DestinyStatus#35]
currently all reputation icons except iron banner don't display.

**Comment by bladefist** [comment]
@adcurtin Thanks! I Didn't know there was a DB update.  This is all fixed up!

**Comment by adcurtin** [comment]
seems broken again

**Comment by bladefist** [comment]
@adcurtin thank you, updated.

**Comment by adcurtin** [comment]
Thanks for the quick fix again!
