### ISSUE TITLE
Suggestion/Request

### ISSUE THREAD

**Issue by stanps** [TrackerNetwork/DestinyStatus#39]
I think it'd be nice to have a site that indicated which of your characters has successfully completed the Black Spindle task.  Would this be something you guys could add to this site?

**Comment by iBotPeaches** [comment]
This is difficult. Yes we can easily detect if you completed the task, by simply checking for that mission on the harder difficulty. However, our system only tracks currently equipped inventory across all 3 characters so finding the gear drops (Spindle, Ship) is not possible.

So what constitutes completing the task? I don't see any field on the mission that corresponds to collecting the weapon and/or gear. The grimoire card for the Black Spindle is once per account, so you can't cross reference it per character. Basically I don't see a way to mark it as completed, unless it was a blanket per account flag (by checking if the Grimoire card for Spindle was obtained)

**Comment by iBotPeaches** [comment]
This has been completed with an "Exotic Quest" tab, not per character because it isn't possible but this should do - https://github.com/TrackerNetwork/DestinyStatus/commit/d07d5b0c201c94114a477304e18c9f407b4088f2
