### ISSUE TITLE
Move all assets to HTTPS

### ISSUE THREAD

**Issue by bladefist** [TrackerNetwork/DestinyStatus#41]
All external assets need to go to https, especially bungie as those are now redirecting.

**Comment by iBotPeaches** [comment]
Done in 5.1 version - https://github.com/iBotPeaches/DestinyStatus/commit/47454afb7658b8141504462d70182febb3215411

Easy to patch into master if urgent.

**Comment by bladefist** [comment]
Thanks! It can wait, no rush. Once we're ready to pull that all in I think I'm going to make the site https only.

**Comment by iBotPeaches** [comment]
This was completed in massive merge of dev to master.
