### ISSUE TITLE
Classified Placeholder

### ISSUE THREAD

**Issue by designgears** [TrackerNetwork/DestinyStatus#45]
http://destinystatus.com/xbl/DG%20DesignGears
http://imgur.com/pzY5QWv

Just as an example, the Outbreak Prime is listed as classified and has a broken image.

_Edit: I'll try to submit a pull request for this if I get some time today._

**Comment by iBotPeaches** [comment]
Thanks for report. I believe this ROI iteration of the API uses `redacted` or some other property to denote classification.

I can patch when I get home tonight if you don't find any time.

**Comment by designgears** [comment]
Sounds good.

Strange things are happening now, I pulled up my desktop at home where I left the page open last night. The info was there, now it's gone. Very odd.

http://imgur.com/JDcbXAS

## Edit:

Seems to be loading normally now, it wasn't showing at all when I left for lunch.

**Comment by iBotPeaches** [comment]
Might have been an manifest update, so now that item is no longer classified. Still need to patch the original problem that redacted/classified items have a dead image. I'll investigate why it is sporadic as well (between dead and working).

My guess is our servers are out of sync on the manifest, so one has the item and another doesn't.
