### ISSUE TITLE
Private Users

### ISSUE THREAD

**Issue by iBotPeaches** [TrackerNetwork/DestinyStatus#46]
I'm not sure what endpoint is protected yet, but a few accounts return

> The user has chosen for this data to be private. No peeking!

So one of the endpoints we use is throwing this and then killing entire viewing of profile. Lets see if we can load a slim view if a private user is encountered.

**Comment by bladefist** [comment]
Ah yes, totally forgot about that.  That's likely the inventory endpoint.

**Comment by bladefist** [comment]
If this is gonna be difficult to fix we can at least put up a notice on the homepage so people know.

**Comment by iBotPeaches** [comment]
Nah, should be easy. Just updating request code to mark some responses as private instead of dying out, then we can just make those tabs with some warning message that data is hidden.
