### ISSUE TITLE
[Request] Add "! This card is bugged" label to bugged grimoire cards.

### ISSUE THREAD

**Issue by louistio** [TrackerNetwork/DestinyStatus#49]
Some grimoire cards have been confirmed bugged, and I think it would be great to be able to display them as such. I think it should be the same icon and color as "This card is unobtainable" for "The Fate of all Fools".

"Khvostov Field Manual, pg. 90" (800312) and "Lady Efrideet" (800407) are currently bugged and are impossible to get.
Source: https://www.bungie.net/en/Forums/Post/213318340

**Comment by iBotPeaches** [comment]
thanks! added.

**Comment by louistio** [comment]
Thanks for quick response. This might look petty, but I really think there should be two different labels. 

The Fate of all Fools is unobtainable for all players (except one) and probably will be forever, but some grimoire cards are only temporarily bugged, and are not necessarily "unobtainable". For example, "Khvostov Field Manual, pg. 90" (800312) is unobtainable for most players, but some players do report they somehow got it, and it appears to be quite random. Also, "Chroma" and "Beauty in Destruction" are both reported bugged by Bungie themselves, yet I still have them. I personally think making a bugged label would answer many questions for cases where a player can't get a grimoire card but some people can for whatever reason.

I understand this could be more complicated to implement, so take your time if you need it, I just believe it would be a great improvement. I could pull request whenever Bungie fixes them too.

**Comment by iBotPeaches** [comment]
Sounds reasonable. We can do that.
