### ISSUE TITLE
Character Ordering

### ISSUE THREAD

**Issue by bladefist** [TrackerNetwork/DestinyStatus#51]
My main is my warlock and it's on the far right and on mobile on the bottom.  [Profile.](http://destinystatus.com/xbl/HT%20xorth).

Need to order better, not sure how.  Number of games? Time played? Last played?

**Comment by bladefist** [comment]
wow that was fast

**Comment by iBotPeaches** [comment]
:) The previous sort was order of character creation, so it was always the same static order. Things will be a bit more volatile now as the order can change, but the community might like that more as quickest to see active character now.

**Comment by frodeknutsen** [comment]
Damn thats a shame. I liked having the characters in a fixed order

**Comment by bladefist** [comment]
@frodeknutsen sorry about that! I didn't know you chose that on purpose.
