### ISSUE TITLE
Statistics are currently unavailable

### ISSUE THREAD

**Issue by bradchoate** [TrackerNetwork/DestinyStatus#55]
I'm seeing this message on the "Stats" tab for my character at:

http://destinystatus.com/xbl/bradchoate

(New account, sure-- but I don't think there are privacy settings that I need to enable, right? The only one I know of is the "Show Destiny advisors" option and that is checked on my Bungie.net account.)

**Comment by iBotPeaches** [comment]
Thanks. We relied on a value that this account had not set (score). It appears `score` is only set and incremented during PVP games, so it was a mistake to use that.

We know use `secondsPlayed` to determine if a character has played. Deployment is going now. Should take ~5 minutes to be live.

**Comment by bradchoate** [comment]
Thanks! This is a subaccount that I'm using for a permadeath run (1 death and I restart the character). So, NO Crucible, ever. :)
