### ISSUE TITLE
Missing app/config folder

### ISSUE THREAD

**Issue by iBotPeaches** [TrackerNetwork/DestinyStatus#6]
Had to cross reference the `composer.json` file to figure out which dependencies needed to be added to `/app/config/app.php` and more. I understand probably db keys, secret keys and so on are in configurations and ENV isn't available in 4.2.

So maybe just commit the stock 4.2 config folder + the dependency needed changes. Developers can add in own api key, db, etc.

**Comment by bladefist** [comment]
It's there now!

**Comment by iBotPeaches** [comment]
thanks :) any skype/hangouts/msn/slack chat? 

Love myself some laravel dev

**Comment by baherramzy** [comment]
Perhaps instructions on how each developer should configure their local config could be added to `readme.md`. As a beginner, it took me a bit too long to figure out why I was getting an invalid API key error.
