### ISSUE TITLE
non https stuff

### ISSUE THREAD

**Issue by iBotPeaches** [TrackerNetwork/DestinyStatus#98]
- [x] favicon 
 - [ ] destinytracker tooltip (disabled until ssl exists)

**Comment by sgtfrankieboy** [comment]
It might be a bit before I have time to make a tooltip script for Destiny 2. It's probably quicker to build it into Destiny Status.

**Comment by iBotPeaches** [comment]
2yr bump lol. Cleaning up the tracker. Working on this again. Don't think we have tooltips, if/when - I can revisit.
